apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2-retain
  volumeMode: Filesystem
  volumeName: pv
